



def check_for_failure(actual, expected):
    if expected != actual:
        print("\nUnexpected result ")
        return True
    return False

